# .goreleaser.yaml
# Configuration for GoReleaser

# --- Build Configuration ---
# Tells GoReleaser where to find the source code and how to compile it.
builds:
  - id: "milk"
    # The entry point of your main package (where main.go is located)
    main: ./main.go

    # The final name of the binary file
    binary: milk

    # List of operating systems to build for
    goos:
      - linux
      - darwin # macOS
      - windows

    # List of architectures to build for
    goarch:
      - amd64
      - arm64

# --- Archive Configuration ---
# Tells GoReleaser how to package the compiled binaries.
archives:
  - id: archive
    # Setting format to 'binary' tells GoReleaser NOT to create .zip or .tar.gz archives.
    # It just uploads the raw compiled executable, which is what your install.sh expects.
    format: binary

# --- Release Configuration ---
# This is where the error occurred before. It MUST be a top-level field.
# The default is to create a release, so we can actually omit this block entirely, 
# but defining it ensures clarity.

# Note: The 'releases:' section is used for settings like draft releases,
# but the core function of creating the release is handled implicitly 
# by the 'release' command in the GitHub Action.
